version: '3'
services:
  go:
    build: ./go
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    working_dir: /root/go
    volumes:
      - ./go:/root/go:cached 
  client:
    build: ./client
    ports:
      - '4200:4200'
    working_dir: /root/client
    volumes:
      - ./client:/root/client:cached