version: '3'
services:
  go:
    build: ./go
    environment:
      - PORT=5000
      - ENV=production
    ports:
      - '5000:5000'
    working_dir: /root/go
    volumes:
      - ./go:/root/go:cached 
  client:
    build: ./client
    environment:
        - ENV=production
    ports:
      - '80:80'
    working_dir: /root/client
    volumes:
      - ./client:/root/client:cached